### ISSUE TITLE
Raspberry Pi Zero, Install problem

### ISSUE THREAD

**Issue by hbarnard** [adafruit/Adafruit_CircuitPython_AM2320#25]
After: 
`pi@raspberrypi:~/projects/temp-sensing $ sudo pip3 install adafruit-circuitpython-am2320`

I end up with:

```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-x_07oobc/sysv-ipc/setup.py", line 11, in <module>
        import prober
      File "/tmp/pip-build-x_07oobc/sysv-ipc/prober.py", line 137
        d["SYSV_IPC_VERSION"] = f'"{version}"'
                                             ^
    SyntaxError: invalid syntax
```

**Comment by caternuson** [comment]
This looks like an older version of Python is being used.

Blinka has a requirement for sysv_ipc version >= 1.1.0:
https://github.com/adafruit/Adafruit_Blinka/blob/809af94ed7982109ea563284daf806a1d167676c/requirements.txt#L6
which can **not** be installed with older versions of Python:
https://github.com/osvenskan/sysv_ipc/issues/14#issuecomment-859993619

What OS release are you running on the Pi?

What versions do you get from these commands?
```
python --version
python2 --version
python3 --version
```

**Comment by caternuson** [comment]
Closing due to lack of response.

Installs OK on test setup:
```
(blinka) pi@raspberrypi:~ $ pip3 --version
pip 18.1 from /home/pi/blinka/lib/python3.7/site-packages/pip (python 3.7)
(blinka) pi@raspberrypi:~ $ pip3 install adafruit-circuitpython-am2320
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting adafruit-circuitpython-am2320
  Downloading https://www.piwheels.org/simple/adafruit-circuitpython-am2320/adafruit_circuitpython_am2320-1.2.11-py3-none-any.whl
Requirement already satisfied: Adafruit-Blinka in ./blinka/lib/python3.7/site-packages (from adafruit-circuitpython-am2320) (6.10.0)
Requirement already satisfied: adafruit-circuitpython-busdevice in ./blinka/lib/python3.7/site-packages (from adafruit-circuitpython-am2320) (5.0.1)
Requirement already satisfied: sysv-ipc>=1.1.0 in ./blinka/lib/python3.7/site-packages (from Adafruit-Blinka->adafruit-circuitpython-am2320) (1.1.0)
Requirement already satisfied: Adafruit-PureIO>=1.1.7 in ./blinka/lib/python3.7/site-packages (from Adafruit-Blinka->adafruit-circuitpython-am2320) (1.1.8)
Requirement already satisfied: pyftdi>=0.40.0 in ./blinka/lib/python3.7/site-packages (from Adafruit-Blinka->adafruit-circuitpython-am2320) (0.51.2)
Requirement already satisfied: RPi.GPIO in ./blinka/lib/python3.7/site-packages (from Adafruit-Blinka->adafruit-circuitpython-am2320) (0.7.0)
Requirement already satisfied: rpi-ws281x>=4.0.0 in ./blinka/lib/python3.7/site-packages (from Adafruit-Blinka->adafruit-circuitpython-am2320) (4.2.5)
Requirement already satisfied: Adafruit-PlatformDetect>=3.13.0 in ./blinka/lib/python3.7/site-packages (from Adafruit-Blinka->adafruit-circuitpython-am2320) (3.13.3)
Requirement already satisfied: pyserial>=3.0 in ./blinka/lib/python3.7/site-packages (from pyftdi>=0.40.0->Adafruit-Blinka->adafruit-circuitpython-am2320) (3.4)
Requirement already satisfied: pyusb>=1.0.0 in ./blinka/lib/python3.7/site-packages (from pyftdi>=0.40.0->Adafruit-Blinka->adafruit-circuitpython-am2320) (1.0.2)
Installing collected packages: adafruit-circuitpython-am2320
Successfully installed adafruit-circuitpython-am2320-1.2.11
(blinka) pi@raspberrypi:~ $ 
```
